"""Regenerate v3 paper tables from corpus_graph_stats.json (fresh from VPS)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "tables" / "corpus_graph_stats.json"
TAB_DIR = ROOT / "tables"

s = json.loads(JSON_PATH.read_text())


def fmt_int(n):
    return f"{n:,}"


def write(path, content):
    p = TAB_DIR / path
    p.write_text(content)
    print(f"  wrote {p.relative_to(ROOT)}")


# ─── corpus_overview.tex ─────────────────────────────────────────
langs = {r["lang"]: r["n"] for r in s["languages"]}
total = s["total_decisions"]
de_n, fr_n, it_n = langs.get("de", 0), langs.get("fr", 0), langs.get("it", 0)
de_pct = 100 * de_n / total
fr_pct = 100 * fr_n / total
it_pct = 100 * it_n / total

write(
    "corpus_overview.tex",
    f"""% Auto-generated by docs/paper/v3/scripts/build_tables.py
\\begin{{table}}[t]
\\centering
\\caption{{OpenCaseLaw corpus overview. Snapshot 2026-05-08.}}
\\label{{tab:corpus}}
\\small
\\begin{{tabular}}{{l r}}
\\toprule
\\textbf{{Quantity}} & \\textbf{{Value}} \\\\
\\midrule
Total decisions & {fmt_int(total)} \\\\
Distinct courts & {s['total_courts']} \\\\
Cantons + federal & {s['total_cantons']} \\\\
Date range & 1875--2026 \\\\
\\addlinespace
German (de) & {fmt_int(de_n)} ({de_pct:.1f}\\%) \\\\
French (fr) & {fmt_int(fr_n)} ({fr_pct:.1f}\\%) \\\\
Italian (it) & {fmt_int(it_n)} ({it_pct:.1f}\\%) \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

# ─── citation_graph.tex ──────────────────────────────────────────
buckets = {r["bucket"]: r["n"] for r in s["in_degree_buckets"]}
ge100 = (
    buckets.get("10000+", 0)
    + buckets.get("1000-9999", 0)
    + buckets.get("100-999", 0)
)
ge1000 = buckets.get("10000+", 0) + buckets.get("1000-9999", 0)
res_pct = 100 * s["rg_resolved_citations"] / s["rg_citation_edges"]

write(
    "citation_graph.tex",
    f"""\\begin{{table}}[t]
\\centering
\\caption{{Citation graph. Edges extracted from federal-court decisions; resolved means the cited target is identified in the corpus.}}
\\label{{tab:citation_graph}}
\\small
\\begin{{tabular}}{{l r}}
\\toprule
\\textbf{{Quantity}} & \\textbf{{Value}} \\\\
\\midrule
Decisions analysed for outgoing citations & {fmt_int(s['rg_decisions'])} \\\\
Citation edges (source $\\to$ target reference) & {fmt_int(s['rg_citation_edges'])} \\\\
Edges with target resolved to a corpus decision & {fmt_int(s['rg_resolved_citations'])} ({res_pct:.1f}\\%) \\\\
Distinct decisions cited at least once & {fmt_int(s['rg_distinct_targets'])} \\\\
Decisions cited $\\geq$ 100 times & {fmt_int(ge100)} \\\\
Decisions cited $\\geq$ 1{{,}}000 times & {fmt_int(ge1000)} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

# ─── cross_lang_citation_matrix.tex ──────────────────────────────
m = {(r["src"], r["tgt"]): r["n"] for r in s["cross_lang_matrix"]}
total_m = sum(m.values())
diag = sum(v for (a, b), v in m.items() if a == b)
off_pct = 100 * (total_m - diag) / total_m


def cell(src, tgt):
    return fmt_int(m.get((src, tgt), 0))


write(
    "cross_lang_citation_matrix.tex",
    f"""\\begin{{table}}[t]
\\centering
\\caption{{Cross-lingual citation matrix. Rows are source decision languages; columns are cited (target) decision languages. Cells give resolved citation edges. Off-diagonal = {fmt_int(total_m - diag)} / {fmt_int(total_m)} = {off_pct:.1f}\\% of all resolved citations.}}
\\label{{tab:cross_lang_citation}}
\\small
\\begin{{tabular}}{{l r r r}}
\\toprule
& \\textbf{{$\\to$ DE}} & \\textbf{{$\\to$ FR}} & \\textbf{{$\\to$ IT}} \\\\
\\midrule
\\textbf{{DE $\\to$}} & {cell('de','de')} & {cell('de','fr')} & {cell('de','it')} \\\\
\\textbf{{FR $\\to$}} & {cell('fr','de')} & {cell('fr','fr')} & {cell('fr','it')} \\\\
\\textbf{{IT $\\to$}} & {cell('it','de')} & {cell('it','fr')} & {cell('it','it')} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

# ─── statute_graph.tex (now includes Materialien) ────────────────
mat = s.get("materialien", {})
mat_docs = mat.get("docs_total", 0)
mat_paras = mat.get("paragraphs", 0)
mat_links = mat.get("article_links", 0)

write(
    "statute_graph.tex",
    f"""\\begin{{table}}[t]
\\centering
\\caption{{Statute and doctrinal graph layers. Decision-to-statute edges plus federal/cantonal mirrors plus Materialien (Federal Council Botschaften) and CC-BY commentaries.}}
\\label{{tab:statute_graph}}
\\small
\\begin{{tabular}}{{l r}}
\\toprule
\\textbf{{Quantity}} & \\textbf{{Value}} \\\\
\\midrule
Decision $\\to$ statute edges & {fmt_int(s['rg_statute_edges'])} \\\\
Distinct provisions referenced & {fmt_int(s['rg_distinct_statutes'])} \\\\
\\addlinespace
Federal laws (Fedlex SR series) & {fmt_int(s['fed_laws'])} \\\\
Federal articles (DE/FR/IT parallel) & {fmt_int(s['fed_articles'])} \\\\
Cantonal laws (all 26 cantons; {len(s.get('cantonal_direct_cantons', []))} direct, {len(s.get('cantonal_fallback_cantons', []))} LexFind fallback) & {fmt_int(s['cantonal_laws'])} \\\\
Cantonal articles & {fmt_int(s['cantonal_articles'])} \\\\
\\addlinespace
Materialien (Botschaft documents, DE/FR/IT) & {fmt_int(mat_docs)} \\\\
Materialien paragraphs (full-text) & {fmt_int(mat_paras)} \\\\
Article-anchored Materialien links & {fmt_int(mat_links)} \\\\
\\addlinespace
Open commentaries (CC-BY) & {fmt_int(s['commentaries_total'])} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

# ─── top_cited.tex ───────────────────────────────────────────────
rows = []
for r in s["top30_cited"][:15]:
    tid = r["target_id"]
    # Render as BGE/ATF/DTF reporter form regardless of the underlying
    # decision_id encoding ("bge_BGE_125_V_351" or "bge_125 V 351").
    if tid.startswith("bge_BGE_"):
        reporter = "BGE " + " ".join(tid[len("bge_BGE_"):].split("_"))
    elif tid.startswith("bge_"):
        reporter = "BGE " + tid[len("bge_"):].replace("_", " ")
    else:
        reporter = tid
    tid_tex = tid.replace("_", "\\_")
    rows.append(f"\\texttt{{{tid_tex}}} & {reporter} & {fmt_int(r['in_degree'])} \\\\")

write(
    "top_cited.tex",
    f"""\\begin{{table}}[t]
\\centering
\\caption{{Top 15 most-cited decisions in the corpus. Subject area inferred from the decision regeste; in-degree counts citing decisions (with multi-citing pairs counted once per source).}}
\\label{{tab:top_cited}}
\\small
\\begin{{tabular}}{{l l r}}
\\toprule
\\textbf{{Decision ID}} & \\textbf{{Reporter form}} & \\textbf{{In-degree}} \\\\
\\midrule
{chr(10).join(rows)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

# ─── top_statutes.tex ────────────────────────────────────────────
rows = []
for r in s["top30_statutes"][:15]:
    rows.append(f"{r['law_code']} & Art.\\ {r['article']} & {fmt_int(r['n'])} \\\\")

write(
    "top_statutes.tex",
    f"""\\begin{{table}}[t]
\\centering
\\caption{{Top 15 most-referenced statutory provisions. \\emph{{LTF}} (French) and \\emph{{BGG}} (German) refer to the same Bundesgerichtsgesetz / Loi sur le Tribunal f\\'ed\\'eral.}}
\\label{{tab:top_statutes}}
\\small
\\begin{{tabular}}{{l l r}}
\\toprule
\\textbf{{Law}} & \\textbf{{Article}} & \\textbf{{Decisions citing}} \\\\
\\midrule
{chr(10).join(rows)}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""",
)

print("\nDone.")
print(f"Snapshot: {total:,} decisions × {s['total_courts']} courts × {s['total_cantons']} cantons")
print(f"Citation graph: {s['rg_citation_edges']:,} edges, {s['rg_resolved_citations']:,} resolved ({res_pct:.1f}%)")
print(f"Statute graph: {s['rg_statute_edges']:,} edges, {s['rg_distinct_statutes']:,} provisions")
print(f"Materialien: {mat_docs:,} docs, {mat_paras:,} paragraphs, {mat_links:,} article links")
